import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="kewords" content="nextjs, huntingcoder blog, Hunting Coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      
        <main className={styles.main}>
          <h1
            className={styles.title}
            priority
          > Hunting Coder </h1>
          <p className={styles.description}>
            A blog for hunting coders
          </p>

          <div className="blogs">
            <h2>Popular Blogs</h2>
            <div className="blogItem">
              <h3>how to learn javascript in 2022</h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
              <h3>how to learn javascript in 2022</h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
              <h3>how to learn javascript in 2022</h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
            </div> 
          </div>
        </main>
    
    </div>
  );
}
