import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2 {
           font-size: 2.5rem;
        }
        h3 {
          font-size: 1.75rem;
          margin-top: 11px;
          margin-bottom: 0;
        }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="kewords" content="nextjs, huntingcoder blog, Hunting Coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeImage.png" alt="HomePage" width={237} height={158} /> */}
          <img className={styles.myImg} src="/homeImage.png" alt="HomePage" width={237} height={158} />
        </div>
        <h1 className={styles.title}>
          &lt;HuntingCoder/&gt;
        </h1>
        
        <div className="blogs">
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>how to learn javascript in 2022</h3>
            <p className={styles.p}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
            <button className={styles.btn}>Read More</button>

            <h3 className={styles.h3}>how to learn javascript in 2022</h3>
            <p className={styles.p}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
            <button className={styles.btn}>Read More</button>

            <h3 className={styles.h3}>how to learn javascript in 2022</h3>
            <p className={styles.p}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor in tenetur blanditiis porro, quasi incidunt earum quam odio deserunt aperiam assumenda quaerat.</p>
            <button className={styles.btn}>Read More</button>
          
          </div>
        </div>
      </main>

    </div>
  );
}
